### ISSUE TITLE
send binary file problem 

### ISSUE THREAD

**Issue by doodoori2** [dropbox/dropbox-api-v2-repl#1]
I tryed to make a python code to upload apk binary file. 
so I wrote under code. 

```
target_path = "/foo" 
send_file = open("bar.apk", "rb")
bytes_read = send_file.read()
send_file.close()
c.up('files/upload', path=target_path, mode='add', _b=bytes_read)
```

Sending text file is success very well. /
but sending binary file raise a excpetion.

```
Traceback (most recent call last):
  File "~/sendfile.py", line 19, in main
    r = c.up('files/upload', path=target_path, mode='add', _b=bytes_read)
  File "~/repl.py", line 96, in up
    with self._request('POST', function, headers, body=body) as r:
  File "~/repl.py", line 136, in _request
    c.request(method, url_path, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 827, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb6 in position 10: ordinal not in range(128)
```

**Comment by doodoori2** [comment]
Thanks for quick response. 
Using python requests package (http://www.python-requests.org/en/latest/) is more simple than using httplib. 
I tried this under code, and with my experience, 
requests package is more faster upload than httplib. 

```
import requests

def up(self, function, *args, **kwargs):
    headers = self._copy_headers(kwargs, 'dropbox-api-arg', 'content-type')

    assert '_b' in kwargs, "Missing body value '_b'"
    body = kwargs.pop('_b')
    assert isinstance(body, bytes), "Expected '_b' to be a bytestring, but got {!r}".format(body)

    api_arg = self._make_api_arg(args, kwargs)
    headers['Dropbox-API-Arg'] = json.dumps(api_arg, ensure_ascii=True)
    headers['Content-Type'] = 'application/octet-stream'

    r = self._request('POST', function, headers, body=body)
    if r.status_code == 200:
        return r.json()
    raise AssertionError("unexpected response : {!r}, {!r}".format(r.status_code, r.text))

def _request(self, method, function, headers, url_params=None, body=None):
    url_path = "/2-beta-2/{}".format(urlparse.quote(function))
    if url_params is not None:
        url_path = url_path + '?' + urlparse.urlencode(list(url_params.items()))
    # hard-coding for post message 
    r = requests.post("http://" + self.hostname + url_path, headers=headers, data=body)
    r.status = r.status_code
    return r
```

but it make a dependency with requests module. 
what do you think about it?

**Comment by cakoose** [comment]
Yeah, I'm intentionally avoiding dependencies.  (This tool is only meant for quick experimentation.  If you want something more full-featured: [dropbox-sdk-python](https://github.com/dropbox/dropbox-sdk-python).)

But I am surprised that `requests` runs faster for you.  Can you reliably reproduce the performance difference?
